version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./static:/work/static
            - ./conf.d/default.conf:/etc/nginx/conf.d/default.conf
