version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - "go"
    go:
        image: golang:1.14
        working_dir: /work
        volumes:
            - ./go:/work
        command: go run .
