version: '3'
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:443"
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./nginx/keys:/work/keys
        depends_on:
            - "go"
    go:
        image: golang:1.14
        working_dir: /work
        volumes:
            - ./go:/work
        command: go run .
